### PR TITLE
Update module.js

### PR DESCRIPTION
**Pull request by jonatanhost**
Added 400% and 600% to font size list.

### CODE REVIEW

**Comment by farski** [comment]
@jonatanhost Could you check in the change to the `src` file also?

**Comment by jonatanhost** [comment]
@farski Have done a pull request on src file

**Comment by farski** [comment]
@jonatanhost Thanks. It looks like there have been some major changes to how Grafana plugins are developed since I last submitted this. I'm going to look into those before I submit a new version, just to make sure there are no incompatibilities. I should be able to get that done this week.

**Comment by jonatanhost** [comment]
@farski Thank you!

I think this is not the best solution but it will work for me!

**Comment by farski** [comment]
I've [submitted](https://github.com/grafana/grafana-plugin-repository/pull/512) a PR to the plugin directory that should solve this. I did it in a slightly different way than your PR to match how the native panels handle font sizes now. Once it gets merged let me know if you run into any trouble.

**Comment by abitrusty** [comment]
Great work guys. Just upgraded to 1.0.2 and font size is fixed. Thanks very much!!

**Pull request closed without merging**
